import type { SemesterOffering } from "@/lib/handbook/types";

export const demoStudentOfferings: SemesterOffering[] = [
  {
    level: 500,
    semester: 1,
    semesterLabel: "First",
    expectedUnits: 20,
    courses: [
      {
        code: "CPE 509",
        title: "Digital System Design with VHDL",
        creditUnits: 2,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
      {
        code: "CPE 521",
        title: "Modelling and Simulation",
        creditUnits: 3,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
      {
        code: "CPE 511",
        title: "Computer Graphics and Animation",
        creditUnits: 2,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
      {
        code: "CPE 591",
        title: "Individual Project I",
        creditUnits: 3,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
      {
        code: "GEC 501",
        title: "Industrial Law and Management",
        creditUnits: 2,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
      {
        code: "CPE 517",
        title: "Artificial Neural Network",
        creditUnits: 2,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
      {
        code: "CPE 525",
        title: "Wireless Networks",
        creditUnits: 2,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
      {
        code: "CPE 507",
        title: "Software Engineering",
        creditUnits: 2,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
    ],
    courseGroups: [
      {
        label: "Plus one elective",
        pickCount: 1,
        sharedUnits: 2,
        options: [
          {
            code: "CPE 515",
            title: "Robotics and Automation",
            creditUnits: 2,
            courseType: "elective",
            prerequisites: [],
            isZeroUnit: false,
          },
          {
            code: "CPE 519",
            title: "Fuzzy Logic and Programming",
            creditUnits: 2,
            courseType: "elective",
            prerequisites: [],
            isZeroUnit: false,
          },
          {
            code: "CPE 513",
            title: "Information Storage and Retrieval",
            creditUnits: 2,
            courseType: "elective",
            prerequisites: [],
            isZeroUnit: false,
          },
        ],
      },
    ],
  },
  {
    level: 500,
    semester: 2,
    semesterLabel: "Second",
    expectedUnits: 23,
    courses: [
      {
        code: "CPE 514",
        title: "Reliability and Maintainability",
        creditUnits: 2,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
      {
        code: "CPE 510",
        title: "Embedded Systems Design",
        creditUnits: 2,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
      {
        code: "CPE 506",
        title: "Cyberpreneurship and Cyber Law",
        creditUnits: 2,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
      {
        code: "CPE 508",
        title: "Computer System Project Management",
        creditUnits: 2,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
      {
        code: "CPE 512",
        title: "Industrial Application Studies",
        creditUnits: 2,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
      {
        code: "GEC 504",
        title: "Industrial Economics",
        creditUnits: 2,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
      {
        code: "CPE 522",
        title: "Cryptography Principles and Applications",
        creditUnits: 2,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
      {
        code: "CPE 592",
        title: "Individual Project II",
        creditUnits: 3,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
      {
        code: "CPE 518",
        title: "Computer Security Techniques",
        creditUnits: 2,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
      {
        code: "CPE 526",
        title: "Applications of FPGA",
        creditUnits: 2,
        courseType: "core",
        prerequisites: [],
        isZeroUnit: false,
      },
    ],
    courseGroups: [
      {
        label: "Plus one elective",
        pickCount: 1,
        sharedUnits: 2,
        options: [
          {
            code: "CPE 502",
            title: "Digital Image Processing",
            creditUnits: 2,
            courseType: "elective",
            prerequisites: [],
            isZeroUnit: false,
          },
          {
            code: "CPE 524",
            title: "Techniques in Data Analysis",
            creditUnits: 2,
            courseType: "elective",
            prerequisites: [],
            isZeroUnit: false,
          },
          {
            code: "CPE 516",
            title: "Expert Systems",
            creditUnits: 2,
            courseType: "elective",
            prerequisites: [],
            isZeroUnit: false,
          },
        ],
      },
    ],
  },
];

export const demoCompletedCourses = [
  "CPE 202",
  "CPE 302",
  "CPE 304",
  "CPE 312",
  "GEC 201",
  "GEC 202",
  "GST 303",
  "ENG 001",
  "ENG 002",
];

export const demoOutstandingCourses = ["GST 202", "CPE 305"];
